import { type FastifyInstance } from "fastify";
import { z } from "zod";
import type { Entity } from "./entity.js";
import {
  registerFindAllRoute,
  registerFindOneRoute,
  registerCreateRoute,
  registerUpdateRoute,
  registerDeleteRoute,
  registerCustomRoutes,
} from "./routes/index.js";
import type { AuthConfig } from "./auth/types.js";
import { createJwtMiddleware } from "./auth/middleware.js";
import { createApiKeyMiddleware } from "./auth/middleware.js";
import { createAuthContextMiddleware } from "./auth/middleware.js";

export type SwaggerConfig = {
  enabled?: boolean;
  title?: string;
  description?: string;
  version?: string;
  routePrefix?: string;
  uiConfig?: {
    docExpansion?: "list" | "full" | "none";
    deepLinking?: boolean;
  };
  auth?: boolean;
};

export type ServerOptions<
  T extends readonly Entity<z.ZodObject<any>>[] = readonly Entity<
    z.ZodObject<any>
  >[],
> = {
  port?: number;
  host?: string;
  entities: T;
  swagger?: SwaggerConfig;
  auth?: AuthConfig;
};

let server: FastifyInstance;
let entities: Map<string, Entity<z.ZodObject<any>>>;


export const startServer = async <
  T extends readonly Entity<z.ZodObject<any>>[],
>(
  fastify: FastifyInstance,
  opts: ServerOptions<T>,
) => {
  server = fastify;
  entities = new Map();

  // Auto-enable auth if any auth method is configured
  const authEnabled = opts.auth?.enabled ?? (opts.auth?.jwt || opts.auth?.apiKey);
  
  // Register authentication middleware if enabled BEFORE registering routes
  if (authEnabled && opts.auth) {
    // Register JWT middleware if configured
    if (opts.auth.jwt) {
      await fastify.register(createJwtMiddleware(opts.auth.jwt));
    }

    // Register API key middleware if configured
    if (opts.auth.apiKey) {
      await fastify.register(createApiKeyMiddleware(opts.auth.apiKey));
    }

    // Register auth context injection middleware
    await fastify.register(createAuthContextMiddleware());
  }

  // Auto-enable Swagger if swagger config is provided
  const swaggerEnabled = opts.swagger?.enabled ?? !!opts.swagger;
  
  // Register Swagger documentation if enabled
  if (swaggerEnabled === true) {
    const swagger = await import("@fastify/swagger");
    await fastify.register(swagger.default, {
      openapi: {
        openapi: "3.0.0",
        info: {
          title: opts.swagger?.title ?? "Frey API",
          description: opts.swagger?.description ?? "Entity-driven API generated by Frey framework",
          version: opts.swagger?.version ?? "1.0.0",
        },
        servers: [
          {
            url: `http://${opts.host ?? "localhost"}:${opts.port ?? 3000}`,
            description: "Development server",
          },
        ],
        tags: opts.entities.map((entity) => ({
          name: entity.name,
          description: `${entity.name} operations`,
        })),
      },
    });

    // Register Swagger UI only if not explicitly disabled
    if (opts.swagger?.enabled === true) {
      const swaggerUi = await import("@fastify/swagger-ui");
      
      // Register Swagger UI with optional authentication
      const swaggerUiOptions: any = {
        routePrefix: opts.swagger?.routePrefix ?? "/documentation",
        uiConfig: {
          docExpansion: opts.swagger?.uiConfig?.docExpansion ?? "full",
          deepLinking: opts.swagger?.uiConfig?.deepLinking ?? false,
        },
        staticCSP: true,
        transformStaticCSP: (header: any) => header,
        transformSpecification: (swaggerObject: any, request: any, reply: any) => {
          return swaggerObject;
        },
        transformSpecificationClone: true,
      };

      // Add authentication hooks if Swagger auth is enabled
      if (opts.swagger?.auth === true) {
        swaggerUiOptions.uiHooks = {
          preHandler: async (request: any, reply: any, next: any) => {
            // Check if user is authenticated
            const auth = (request as any).auth;
            if (!auth?.isAuthenticated || !auth?.user) {
              // Redirect to login URL if provided in global auth config
              if (opts.auth?.loginUrl) {
                reply.redirect(opts.auth.loginUrl);
                return;
              }
              
              // Fallback: redirect to a default login page
              reply.redirect("/login");
              return;
            }
            next();
          },
        };
      }

      await fastify.register(swaggerUi.default, swaggerUiOptions);
    }
  }

  opts.entities.forEach((entity) => {
    entities.set(entity.name, entity);

    // Register all CRUD routes with RBAC configuration
    registerFindAllRoute(server, entity, opts.auth);
    registerFindOneRoute(server, entity, opts.auth);
    registerCreateRoute(server, entity, opts.auth);
    registerUpdateRoute(server, entity, opts.auth);
    registerDeleteRoute(server, entity, opts.auth);

    // Register custom routes
    registerCustomRoutes(server, entity, opts.auth);
  });

  try {
    await fastify.listen({ port: opts.port ?? 3000, host: opts.host });
    fastify.log.info(`Server listening on http://${opts.host ?? "localhost"}:${opts.port ?? 3000}`);
    
    if (opts.swagger?.enabled !== false) {
      const routePrefix = opts.swagger?.routePrefix ?? "/documentation";
      fastify.log.info(`API documentation available at http://${opts.host ?? "localhost"}:${opts.port ?? 3000}${routePrefix}`);
    }
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
