import { type FastifyInstance } from "fastify";
import { z } from "zod";
import type { Entity } from "./entity.js";
import {
  registerFindAllRoute,
  registerFindOneRoute,
  registerCreateRoute,
  registerUpdateRoute,
  registerDeleteRoute,
  registerCustomRoutes,
} from "./routes/index.js";
import type { AuthConfig } from "./auth/types.js";
import { createJwtMiddleware } from "./auth/middleware.js";
import { createApiKeyMiddleware } from "./auth/middleware.js";
import { setCqrsEventBus } from "./cqrs/state.js";
import { createInMemoryCqrsEventBus, defaultCqrsEventBus } from "./cqrs/index.js";
import type { CqrsEventBus } from "./cqrs/types.js";
import type { CqrsConfig } from "./cqrs/types.js";
import type { CacheConfig } from "./cache/types.js";
import { createInMemoryCacheStore } from "./cache/memory-store.js";
import { setCacheConfig } from "./cache/state.js";
import type { FastifyCorsOptions } from "@fastify/cors";

export type SwaggerConfig = {
  enabled?: boolean;
  title?: string;
  description?: string;
  version?: string;
  routePrefix?: string;
  uiConfig?: {
    docExpansion?: "list" | "full" | "none";
    deepLinking?: boolean;
  };
  auth?: boolean;
};

export type CorsConfig = {
  enabled?: boolean;
  origin?: string | string[] | boolean;
};

export type ServerOptions<
  T extends readonly Entity<z.ZodObject<any>>[] = readonly Entity<
    z.ZodObject<any>
  >[],
> = {
  port?: number;
  host?: string;
  entities: T;
  swagger?: SwaggerConfig;
  auth?: AuthConfig;
  cors?: CorsConfig;
  cqrs?: CqrsConfig;
  cache?: CacheConfig;
  websocket?: {
    enabled?: boolean;
  };
  health?: {
    enabled?: boolean;
    routePrefix?: string;
  };
};

let server: FastifyInstance;
let entities: Map<string, Entity<z.ZodObject<any>>>;
let cqrsEventBus: CqrsEventBus;

export const registerFrey = async <
  T extends readonly Entity<z.ZodObject<any>>[],
>(
  fastify: FastifyInstance,
  opts: ServerOptions<T>,
) => {
  server = fastify;
  entities = new Map();

  // Auto-enable auth if any auth method is configured
  const authEnabled = opts.auth?.enabled ?? (opts.auth?.jwt || opts.auth?.apiKey);

  const cqrsEnabled = opts.cqrs?.enabled ?? false;
  const cqrsEventBus = cqrsEnabled
    ? opts.cqrs?.eventBus ?? createInMemoryCqrsEventBus()
    : defaultCqrsEventBus();
  setCqrsEventBus(cqrsEventBus);

  const cacheEnabled = opts.cache?.enabled ?? false;
  const cacheStore = cacheEnabled
    ? opts.cache?.store ?? createInMemoryCacheStore()
    : undefined;
  setCacheConfig(fastify, {
    enabled: cacheEnabled,
    store: cacheStore,
    keyPrefix: opts.cache?.keyPrefix,
  });

  // Always provide a neutral auth context shape so entity handlers can rely on
  // `context.auth` existing even when auth is disabled for the route.
  fastify.addHook("preHandler", async (request) => {
    if (!(request as any).auth) {
      (request as any).auth = { isAuthenticated: false };
    }
  });

  // Register authentication middleware if enabled BEFORE registering routes
  if (authEnabled && opts.auth) {
    // Register JWT middleware if configured
    if (opts.auth.jwt) {
      await fastify.register(createJwtMiddleware(opts.auth.jwt));
    }

    // Register API key middleware if configured
    if (opts.auth.apiKey) {
      await fastify.register(createApiKeyMiddleware(opts.auth.apiKey));
    }
  }

  const corsEnabled = opts.cors?.enabled ?? false;
  if (corsEnabled) {
    const cors = await import("@fastify/cors");
    await fastify.register(cors.default, {
      origin: opts.cors?.origin ?? true,
    });
  }

  // Auto-enable Swagger if swagger config is provided
  const swaggerEnabled = opts.swagger?.enabled ?? !!opts.swagger;

  // Register Swagger documentation if enabled
  if (swaggerEnabled === true) {
    const swagger = await import("@fastify/swagger");
    await fastify.register(swagger.default, {
      openapi: {
        openapi: "3.0.0",
        info: {
          title: opts.swagger?.title ?? "Frey API",
          description:
            opts.swagger?.description ??
            "Entity-driven API generated by Frey framework",
          version: opts.swagger?.version ?? "1.0.0",
        },
        servers: [
          {
            url: `http://${opts.host ?? "localhost"}:${opts.port ?? 3000}`,
            description: "Development server",
          },
        ],
        tags: opts.entities.map((entity) => ({
          name: entity.name,
          description: `${entity.name} operations`,
        })),
      },
    });

    // Register Swagger UI only if not explicitly disabled
    if (opts.swagger?.enabled === true) {
      const swaggerUi = await import("@fastify/swagger-ui");

      // Register Swagger UI with optional authentication
      const swaggerUiOptions: any = {
        routePrefix: opts.swagger?.routePrefix ?? "/documentation",
        uiConfig: {
          docExpansion: opts.swagger?.uiConfig?.docExpansion ?? "full",
          deepLinking: opts.swagger?.uiConfig?.deepLinking ?? false,
        },
        staticCSP: true,
        transformStaticCSP: (header: any) => header,
        transformSpecification: (swaggerObject: any, _request: any, _reply: any) => {
          return swaggerObject;
        },
        transformSpecificationClone: true,
      };

      // Add authentication hooks if Swagger auth is enabled
      if (opts.swagger?.auth === true) {
        swaggerUiOptions.uiHooks = {
          preHandler: async (
            request: any,
            reply: any,
            next: any,
          ) => {
            // Check if user is authenticated
            const auth = (request as any).auth;
            if (!auth?.isAuthenticated || !auth?.user) {
              // Redirect to login URL if provided in global auth config
              if (opts.auth?.loginUrl) {
                reply.redirect(opts.auth.loginUrl);
                return;
              }

              // Fallback: redirect to a default login page
              reply.redirect("/login");
              return;
            }
            next();
          },
        };
      }

      await fastify.register(swaggerUi.default, swaggerUiOptions);
    }
  }

  if (opts.websocket?.enabled) {
    const websocketPlugin = await import("@fastify/websocket");
    await fastify.register(websocketPlugin.default);
  }

  const healthEnabled = opts.health?.enabled ?? false;
  if (healthEnabled) {
    const routePrefix = opts.health?.routePrefix ?? "/health";
    fastify.get(`${routePrefix}/live`, async (_request, reply) => {
      reply.send({ status: "ok", check: "liveness" });
    });
    fastify.get(`${routePrefix}/ready`, async (_request, reply) => {
      reply.send({ status: "ok", check: "readiness" });
    });
  }

  opts.entities.forEach((entity) => {
    entities.set(entity.name, entity);

    // Register all CRUD routes with RBAC configuration
    registerFindAllRoute(server, entity, opts.auth);
    registerFindOneRoute(server, entity, opts.auth);
    registerCreateRoute(server, entity, opts.auth);
    registerUpdateRoute(server, entity, opts.auth);
    registerDeleteRoute(server, entity, opts.auth);

    // Register custom routes
    registerCustomRoutes(server, entity, opts.auth);
  });
};

export const startServer = async <
  T extends readonly Entity<z.ZodObject<any>>[],
>(
  fastify: FastifyInstance,
  opts: ServerOptions<T>,
) => {
  await registerFrey(fastify, opts);

  try {
    await fastify.listen({ port: opts.port ?? 3000, host: opts.host });
    fastify.log.info(`Server listening on http://${opts.host ?? "localhost"}:${opts.port ?? 3000}`);
    
    if (opts.swagger?.enabled !== false) {
      const routePrefix = opts.swagger?.routePrefix ?? "/documentation";
      fastify.log.info(`API documentation available at http://${opts.host ?? "localhost"}:${opts.port ?? 3000}${routePrefix}`);
    }
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
