name: Security

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2 AM UTC
  workflow_dispatch:
  push:
    branches: [ main, proto ]

jobs:
  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        
      - name: Check for known vulnerabilities
        run: |
          npx audit-ci --config audit-ci.json || echo "Vulnerabilities found - check audit-ci.json config"
          
      - name: Generate security report
        run: |
          echo "# Security Report" > security-report.md
          echo "Generated on: $(date)" >> security-report.md
          echo "" >> security-report.md
          echo "## NPM Audit Results" >> security-report.md
          npm audit --json > audit-results.json || echo "Audit completed with issues"
          
      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report-${{ github.run_number }}
          path: |
            security-report.md
            audit-results.json
          retention-days: 30

  code-scan:
    name: Code Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
        continue-on-error: true
        
      - name: Upload CodeQL results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codeql-results-${{ github.run_number }}
          path: |
            results/
            codeql-database/
          retention-days: 30

  dependency-update-check:
    name: Dependency Update Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for outdated packages
        run: |
          echo "# Outdated Packages Report" > outdated-report.md
          echo "Generated on: $(date)" >> outdated-report.md
          echo "" >> outdated-report.md
          npx npm-check-updates --format group >> outdated-report.md || echo "No outdated packages found"
          
      - name: Upload outdated report
        uses: actions/upload-artifact@v4
        with:
          name: outdated-report-${{ github.run_number }}
          path: outdated-report.md
          retention-days: 30

  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check licenses
        run: |
          echo "# License Report" > license-report.md
          echo "Generated on: $(date)" >> license-report.md
          echo "" >> license-report.md
          npx license-checker --summary >> license-report.md || echo "License check completed"
          
      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: license-report-${{ github.run_number }}
          path: license-report.md
          retention-days: 30
